### ISSUE TITLE
Feature Request: Add comment to PR to link to preview outputs

### ISSUE THREAD

**Issue by michaeltlombardi** [robert-matusewicz/leanpub-preview-action#2]
## User Story

```yaml
As an: author using this GitHub Action
I would like: to be able to click the links to download/view preview outputs from a PR which triggers the preview build
So that: I can review the output without having to navigate manually to the correct page on LeanPub
```
